version: '3.9'
services:
  userbot:
    build: .
    image: goodmorning-userbot
    container_name: goodmorning-userbot
    restart: always
    volumes:
      - ./config.toml:/etc/goodmorninguserbot.toml:ro
    command: [ "--config", "/etc/goodmorninguserbot.toml" ]
